#pragma once
#include <fstream>
#include <cmath>
#include <cstdlib>
#include <vector>
#include <string>
#include <chrono>
#include <thread>

#include "include/rapidjson/document.h"
#include "include/rapidjson/istreamwrapper.h"
#include <iostream>
#include <algorithm>
#include <limits>
#include "yordanMath.h"
#include "Color.h"
#include "vec3.h"
#include <functional>
#include <mutex>
#include <stack>

#include "Material.h"
#include "triangle.h"
#include "Matrix.h"
#include "Mesh.h"
#include "Camera.h"
#include "Settings.h"
#include "Light.h"
#include "Texture.h"
#include "IntersectionData.h"
#include "Scene.h"
#include "Ray.h"
#include "Bucket.h"
#include "AABB.h"
#include "AccTreeNode.h"
#include "AccTree.h"