#pragma once
#include <fstream>
#include <cmath>
#include <cstdlib>
#include <vector>
#include <string>
#include "include/rapidjson/document.h"
#include "include/rapidjson/istreamwrapper.h"
#include <iostream>
#include <algorithm>
#include <limits>
#include "Math.h"
#include "Color.h"
#include "vec3.h"
#include "Ray.h"
#include "Material.h"
#include "triangle.h"
#include "Matrix.h"
#include "Mesh.h"
#include "Camera.h"
#include "Settings.h"
#include "Light.h"